### ISSUE TITLE
Добавить команду /help

### ISSUE THREAD

**Issue by marylorian** [razrabs-media/rzrbs-vacancy-bot#35]
- [x] написать текст для сообщения по вызову команды `/help`
- [x] добавить команду в код бота

**Comment by raantoniv** [comment]
Привет! Я готов помочь тебе опубликовать вакансию в нашем канале. Для этого, пожалуйста, отправь мне следующую информацию о вакансии:

1. Кому: (укажите искомого специалиста)
2. Опыт работы: (укажите требуемый опыт работы)
3. З/П: (укажите зарплатный диапазон, например, "от 50 000 рублей" или "по договоренности")
4. Компания: (укажите название компании, которая осуществляет поиск)
5. Процесс найма: (опишите процесс найма, если есть особые этапы или требования)
6. Описание: (дайте подробное описание вакансии)

Пример вакансии:
```
Кому: Middle Frontend Developer
Опыт работы: от 2 лет
З/П: от 200 000 рублей
Компания: MyITCompany
Процесс найма: 1. Отправка резюме, 2. Техническое интервью, 3. Собеседование с руководителем

Мы ищем опытного разработчика. Отличное знание HTML, CSS, JavaScript. Опыт работы с фреймворками React или Vue. Готовность к командной работе и умение решать сложные задачи. Предлагаем интересные проекты и конкурентную зарплату.
```

Если есть дополнительные требования, такие как ограничение по локации или требования к иностранному языку, пожалуйста, укажи их также.
