### ISSUE TITLE
Добавить сообщения/кнопки для проверки парсинга

### ISSUE THREAD

**Issue by marylorian** [razrabs-media/rzrbs-vacancy-bot#37]
добавить логику в код

сформулировать тексты для
- [x] кнопки одобрения вакансии после парсинга
- [x] кнопки отклонение вакансии после парсинга 
- [x] кнопки повторного парсинга
- [x] сообщения ожидания парсинга

**Comment by marylorian** [comment]
- Сообщение о начале процесса:
Обрабатываю текст, это не займет много времени...

- Сообщение о проваленной валидации:
Текст не прошел проверку, пожалуйста, убедись, что в сообщении указаны основные поля. Для ознакомления с правилами публикации вызови команду /help, либо свяжись с администратором для решения возникшей проблемы

- Сообщение об исчерапании лимита (личное)
У тебя закончились слоты для бесплатного размещения вакансий. Новые слоты будут доступны с первого дня следующего месяца. Ты также можешь связаться с администратором для публикации сверх лимита

- Сообщение об исчерпании лимита (компания)
Для этой компании достигнут месячный лимит бесплатных публикаций. Ты можешь опубликовать вакансии от других компаний, либо связаться с администратором для публикации сверх лимита

- Сообщение о забитой очереди
Увы! В этом месяце очень плотное расписание, я не могу поместить вакансии в очередь. При большом запросе от разных людей и компаний ограничения будут снижены, а сейчас ты можешь обратиться к администратору, чтобы опубликовать вне очереди.

- Сообщение о системной ошибке
Что-то пошло не так, я плохо себя чувствую! Позови администратора!

- Сообщение о поиске свободных слотов
- Секунду, ищу свободные слоты...

**Comment by raantoniv** [comment]
> добавить логику в код
> 
> сформулировать тексты для
> 
> * [ ]  кнопки одобрения вакансии после парсинга
> * [ ]  кнопки отклонение вакансии после парсинга
> * [ ]  кнопки повторного парсинга
> * [x]  сообщения ожидания парсинга

Текст кнопки одобрения парсинга: Опубликовать
Текст кнопки отклонения вакансии: Отменить
Текст кнопки повторного парсинга: Попробовать еще раз

**Comment by raantoniv** [comment]
Перед отправкой превью, под которым размещены кнопки, бот отправляет сообщение:

"Вакансия сформирована. В случае некорректной обработке текста попробуй снова или свяжись с администратором после нескольких попыток"
